repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: ["--line-length", "100"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: []
        args: ["--show-error-codes", "--pretty", "--python-version", "3.12", "src"]
        pass_filenames: false

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -lc 'ALLOWED_CLIENT_KEYS=dev-key-1 PYTHONPATH=src pytest -q'
        language: system
        pass_filenames: false
