name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pre-commit install-hooks
      - name: Lint (ruff)
        run: ruff check .
      - name: Format check (black)
        run: black --check .
      - name: Type check (mypy)
        env:
          MYPYPATH: src
        run: mypy src
      - name: Pre-commit (all files)
        run: pre-commit run --all-files --show-diff-on-failure
      - name: Tests (pytest with coverage)
        env:
          PYTHONPATH: src
          ALLOWED_CLIENT_KEYS: dev-key-1
        run: pytest --cov=src --cov-report=term-missing --cov-fail-under=85
